// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NguyenVanHuan782.Data;

#nullable disable

namespace NguyenVanHuan782.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240106072345_Create_table_Doituong2")]
    partial class Create_table_Doituong2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("NguyenVanHuan782.Models.Doituong2", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Diachi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StudenID")
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.HasIndex("StudenID");

                    b.ToTable("Doituong2");
                });

            modelBuilder.Entity("NguyenVanHuan782.Models.Student", b =>
                {
                    b.Property<string>("StudentID")
                        .HasColumnType("TEXT");

                    b.Property<float>("SDT")
                        .HasColumnType("REAL");

                    b.Property<int>("SoDinhDanh")
                        .HasColumnType("INTEGER");

                    b.HasKey("StudentID");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("NguyenVanHuan782.Models.Doituong2", b =>
                {
                    b.HasOne("NguyenVanHuan782.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudenID");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
